# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/lpel
pkgincludedir = $(includedir)/lpel
pkglibdir = $(libdir)/lpel
pkglibexecdir = $(libexecdir)/lpel
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
DIST_COMMON = $(srcdir)/Makefile_scc.am $(srcdir)/Makefile.in \
	$(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(top_srcdir)/build-aux/depcomp AUTHORS \
	README build-aux/compile build-aux/config.guess \
	build-aux/config.sub build-aux/depcomp build-aux/install-sh \
	build-aux/missing build-aux/ltmain.sh \
	$(top_srcdir)/build-aux/compile \
	$(top_srcdir)/build-aux/config.guess \
	$(top_srcdir)/build-aux/config.sub \
	$(top_srcdir)/build-aux/install-sh \
	$(top_srcdir)/build-aux/ltmain.sh \
	$(top_srcdir)/build-aux/missing
#am__append_1 = -DUSE_MTX_PCL
##am__append_2 = src/ctx/ctx_i386.S
##am__append_3 = src/ctx/ctx_amd64.S
##am__append_4 = src/ctx/ctx_amd64-mem.S
am__append_5 = -DUSE_MTX_PCL
am__append_6 = -DUSE_MTX_PCL
#am__append_7 = src/ctx/ctx_i386.S
#am__append_8 = src/ctx/ctx_i386.S
#am__append_9 = src/ctx/ctx_amd64.S
#am__append_10 = src/ctx/ctx_amd64.S
#am__append_11 = src/ctx/ctx_amd64-mem.S
#am__append_12 = src/ctx/ctx_amd64-mem.S
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_pthread.m4 \
	$(top_srcdir)/m4/ax_tls.m4 $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
am__DEPENDENCIES_1 =
liblpel_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_1)
am__liblpel_la_SOURCES_DIST = src/mailbox.c src/streamset.c \
	src/timing.c src/lpelcfg.c src/lpel_main.c src/lpel_hwloc.c \
	src/sched/decentralised/sema.c \
	src/sched/decentralised/decen_scheduler.c \
	src/sched/decentralised/decen_scheduler.h \
	src/sched/decentralised/spmdext.c \
	src/sched/decentralised/spmdext.h \
	src/sched/decentralised/decen_task.c \
	src/sched/decentralised/decen_task.h \
	src/sched/decentralised/task_migration.h \
	src/sched/decentralised/task_migration.c \
	src/sched/decentralised/decen_worker.c \
	src/sched/decentralised/decen_worker.h \
	src/sched/decentralised/decen_taskqueue.c \
	src/sched/decentralised/decen_taskqueue.h \
	src/sched/decentralised/decen_stream.c \
	src/sched/decentralised/decen_stream.h \
	src/sched/decentralised/decen_buffer.c \
	src/sched/decentralised/decen_buffer.h src/ctx/ctx_i386.S \
	src/ctx/ctx_amd64.S src/ctx/ctx_amd64-mem.S
am__dirstamp = $(am__leading_dot)dirstamp
#am__objects_1 = src/ctx/liblpel_la-ctx_i386.lo
#am__objects_2 = src/ctx/liblpel_la-ctx_amd64.lo
#am__objects_3 = src/ctx/liblpel_la-ctx_amd64-mem.lo
am_liblpel_la_OBJECTS = src/liblpel_la-mailbox.lo \
	src/liblpel_la-streamset.lo \
	src/liblpel_la-timing.lo \
	src/liblpel_la-lpelcfg.lo \
	src/liblpel_la-lpel_main.lo \
	src/liblpel_la-lpel_hwloc.lo \
	src/sched/decentralised/liblpel_la-sema.lo \
	src/sched/decentralised/liblpel_la-decen_scheduler.lo \
	src/sched/decentralised/liblpel_la-spmdext.lo \
	src/sched/decentralised/liblpel_la-decen_task.lo \
	src/sched/decentralised/liblpel_la-task_migration.lo \
	src/sched/decentralised/liblpel_la-decen_worker.lo \
	src/sched/decentralised/liblpel_la-decen_taskqueue.lo \
	src/sched/decentralised/liblpel_la-decen_stream.lo \
	src/sched/decentralised/liblpel_la-decen_buffer.lo \
	$(am__objects_1) $(am__objects_2) \
	$(am__objects_3)
liblpel_la_OBJECTS = $(am_liblpel_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
am_liblpel_la_rpath = -rpath $(libdir)
liblpel_hrc_la_DEPENDENCIES =  \
	$(am__DEPENDENCIES_1)
#liblpel_hrc_la_DEPENDENCIES =  \
#	$(am__DEPENDENCIES_1)
am__liblpel_hrc_la_SOURCES_DIST = src/mailbox.c src/streamset.c \
	src/timing.c src/lpelcfg.c src/lpel_main.c src/lpel_hwloc.c \
	src/sched/hierarchy/hrc_task.c src/sched/hierarchy/hrc_task.h \
	src/sched/hierarchy/hrc_worker_init.c \
	src/sched/hierarchy/hrc_worker_op.c \
	src/sched/hierarchy/hrc_worker.h \
	src/sched/hierarchy/hrc_taskqueue.c \
	src/sched/hierarchy/hrc_taskqueue.h \
	src/sched/hierarchy/taskpriority.h \
	src/sched/hierarchy/taskpriority.c \
	src/sched/hierarchy/hrc_stream.c \
	src/sched/hierarchy/hrc_stream.h \
	src/sched/hierarchy/hrc_buffer.c \
	src/sched/hierarchy/hrc_buffer.h src/ctx/ctx_i386.S \
	src/ctx/ctx_amd64.S src/ctx/ctx_amd64-mem.S \
	src/sched/hierarchy/scc/scc_worker_init.c \
	src/sched/hierarchy/scc/scc_mailbox.c
#am__objects_4 = src/ctx/liblpel_hrc_la-ctx_i386.lo
#am__objects_5 = src/ctx/liblpel_hrc_la-ctx_amd64.lo
#am__objects_6 = src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo
##am__objects_7 = src/ctx/liblpel_hrc_la-ctx_i386.lo
##am__objects_8 = src/ctx/liblpel_hrc_la-ctx_amd64.lo
##am__objects_9 = src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo
am_liblpel_hrc_la_OBJECTS =  \
	src/liblpel_hrc_la-mailbox.lo \
	src/liblpel_hrc_la-streamset.lo \
	src/liblpel_hrc_la-timing.lo \
	src/liblpel_hrc_la-lpelcfg.lo \
	src/liblpel_hrc_la-lpel_main.lo \
	src/liblpel_hrc_la-lpel_hwloc.lo \
	src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo \
	src/sched/hierarchy/liblpel_hrc_la-hrc_worker_init.lo \
	src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo \
	src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo \
	src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo \
	src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo \
	src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo \
	$(am__objects_4) $(am__objects_5) \
	$(am__objects_6)
#am_liblpel_hrc_la_OBJECTS =  \
#	src/liblpel_hrc_la-streamset.lo \
#	src/liblpel_hrc_la-timing.lo \
#	src/liblpel_hrc_la-lpelcfg.lo \
#	src/liblpel_hrc_la-lpel_main.lo \
#	src/liblpel_hrc_la-lpel_hwloc.lo \
#	src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo \
#	src/sched/hierarchy/scc/liblpel_hrc_la-scc_worker_init.lo \
#	src/sched/hierarchy/scc/liblpel_hrc_la-scc_mailbox.lo \
#	src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo \
#	src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo \
#	src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo \
#	src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo \
#	src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo \
#	$(am__objects_7) $(am__objects_8) \
#	$(am__objects_9) $(am__objects_4) \
#	$(am__objects_5) $(am__objects_6)
liblpel_hrc_la_OBJECTS = $(am_liblpel_hrc_la_OBJECTS)
am_liblpel_hrc_la_rpath = -rpath $(libdir)
#am_liblpel_hrc_la_rpath = -rpath $(libdir)
liblpel_mon_la_LIBADD =
am__liblpel_mon_la_SOURCES_DIST = modimpl/monitoring.c \
	modimpl/monitoring.h
am_liblpel_mon_la_OBJECTS =  \
	modimpl/liblpel_mon_la-monitoring.lo
#am_liblpel_mon_la_OBJECTS =  \
#	modimpl/liblpel_mon_la-monitoring.lo
liblpel_mon_la_OBJECTS = $(am_liblpel_mon_la_OBJECTS)
am_liblpel_mon_la_rpath = -rpath $(libdir)
#am_liblpel_mon_la_rpath = -rpath $(libdir)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CPPASCOMPILE = $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS)
LTCPPASCOMPILE = $(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CCASFLAGS) $(CCASFLAGS)
AM_V_CPPAS = $(am__v_CPPAS_$(V))
am__v_CPPAS_ = $(am__v_CPPAS_$(AM_DEFAULT_VERBOSITY))
am__v_CPPAS_0 = @echo "  CPPAS   " $@;
am__v_CPPAS_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(liblpel_la_SOURCES) $(liblpel_hrc_la_SOURCES) \
	$(liblpel_mon_la_SOURCES)
DIST_SOURCES = $(am__liblpel_la_SOURCES_DIST) \
	$(am__liblpel_hrc_la_SOURCES_DIST) \
	$(am__liblpel_mon_la_SOURCES_DIST)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
DIST_TARGETS = dist-bzip2 dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /mnt/snet/lpel-master/build-aux/missing aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
AUTOCONF = ${SHELL} /mnt/snet/lpel-master/build-aux/missing autoconf
AUTOHEADER = ${SHELL} /mnt/snet/lpel-master/build-aux/missing autoheader
AUTOMAKE = ${SHELL} /mnt/snet/lpel-master/build-aux/missing automake-1.14
AWK = mawk
CC = gcc -std=gnu99
CCAS = gcc -std=gnu99
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g -O2
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -pthread
CPP = gcc -std=gnu99 -E
CPPFLAGS =  -I/mnt/snet/pcl-1.12/include
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"lpel\" -DPACKAGE_TARNAME=\"lpel\" -DPACKAGE_VERSION=\"1.x\" -DPACKAGE_STRING=\"lpel\ 1.x\" -DPACKAGE_BUGREPORT=\"daniel.prokesch@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PCL=1 -DUSE_MCTX_PCL=1 -DHAVE_PTHREAD=1 -DHAVE_SYSCONF=1 -DHAVE_PTHREAD_SPIN_INIT=1 -DHAVE_PTHREAD_SETAFFINITY_NP=1 -DHAVE_POSIX_SEMAPHORES=1 -DHAVE_POSIX_TIMERS=1 -DHAVE_SYNC_ATOMIC_BUILTINS=1 -DTLSSPEC=__thread -DHAVE___THREAD=1
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBPCL_LA = /mnt/snet/pcl-1.12/pcl/libpcl.la
LIBS =  
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = cp -pR
LTLIBOBJS = 
MAKEINFO = ${SHELL} /mnt/snet/lpel-master/build-aux/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = lpel
PACKAGE_BUGREPORT = daniel.prokesch@gmail.com
PACKAGE_NAME = lpel
PACKAGE_STRING = lpel 1.x
PACKAGE_TARNAME = lpel
PACKAGE_URL = 
PACKAGE_VERSION = 1.x
PATH_SEPARATOR = :
PTHREAD_CC = gcc -std=gnu99
PTHREAD_CFLAGS = -pthread
PTHREAD_LIBS = 
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 1.x
abs_builddir = /mnt/snet/lpel-master
abs_srcdir = /mnt/snet/lpel-master
abs_top_builddir = /mnt/snet/lpel-master
abs_top_srcdir = /mnt/snet/lpel-master
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
ax_pthread_config = 
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /mnt/snet/lpel-master/build-aux/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /mnt/snet/lpel-master
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
SUBDIRS = include .
lib_LTLIBRARIES = liblpel.la liblpel_mon.la liblpel_hrc.la 
#lib_LTLIBRARIES = liblpel_mon.la liblpel_hrc.la 
liblpel_hrc_la_SOURCES = src/mailbox.c src/streamset.c \
	src/timing.c src/lpelcfg.c src/lpel_main.c \
	src/lpel_hwloc.c src/sched/hierarchy/hrc_task.c \
	src/sched/hierarchy/hrc_task.h \
	src/sched/hierarchy/hrc_worker_init.c \
	src/sched/hierarchy/hrc_worker_op.c \
	src/sched/hierarchy/hrc_worker.h \
	src/sched/hierarchy/hrc_taskqueue.c \
	src/sched/hierarchy/hrc_taskqueue.h \
	src/sched/hierarchy/taskpriority.h \
	src/sched/hierarchy/taskpriority.c \
	src/sched/hierarchy/hrc_stream.c \
	src/sched/hierarchy/hrc_stream.h \
	src/sched/hierarchy/hrc_buffer.c \
	src/sched/hierarchy/hrc_buffer.h \
	$(am__append_8) $(am__append_10) \
	$(am__append_12)
#liblpel_hrc_la_SOURCES = src/streamset.c src/timing.c \
#	src/lpelcfg.c src/lpel_main.c src/lpel_hwloc.c \
#	src/sched/hierarchy/hrc_task.c \
#	src/sched/hierarchy/hrc_task.h \
#	src/sched/hierarchy/scc/scc_worker_init.c \
#	src/sched/hierarchy/scc/scc_mailbox.c \
#	src/sched/hierarchy/hrc_worker_op.c \
#	src/sched/hierarchy/hrc_worker.h \
#	src/sched/hierarchy/hrc_taskqueue.c \
#	src/sched/hierarchy/hrc_taskqueue.h \
#	src/sched/hierarchy/taskpriority.h \
#	src/sched/hierarchy/taskpriority.c \
#	src/sched/hierarchy/hrc_stream.c \
#	src/sched/hierarchy/hrc_stream.h \
#	src/sched/hierarchy/hrc_buffer.c \
#	src/sched/hierarchy/hrc_buffer.h $(am__append_2) \
#	$(am__append_3) $(am__append_4) $(am__append_8) \
#	$(am__append_10) $(am__append_12)
liblpel_hrc_la_CPPFLAGS = -I$(top_srcdir)/include \
	-I$(top_srcdir)/src/include \
	-I$(top_srcdir)/src/include/OpenComRTOS/posix32/include \
	$(am__append_6)
#liblpel_hrc_la_CPPFLAGS = -I$(top_srcdir)/include \
#	-I$(top_srcdir)/src/include $(am__append_1) \
#	$(am__append_6)
liblpel_mon_la_SOURCES = \
	modimpl/monitoring.c \
	modimpl/monitoring.h

#liblpel_mon_la_SOURCES = \
#	modimpl/monitoring.c \
#	modimpl/monitoring.h

liblpel_mon_la_CPPFLAGS = -I$(top_srcdir)/include
#liblpel_mon_la_CPPFLAGS = -I$(top_srcdir)/include
liblpel_hrc_la_LIBADD = $(LIBPCL_LA)
#liblpel_hrc_la_LIBADD = $(LIBPCL_LA)
ACLOCAL_AMFLAGS = -I m4
#ACLOCAL_AMFLAGS = -I m4
liblpel_la_SOURCES = src/mailbox.c src/streamset.c \
	src/timing.c src/lpelcfg.c src/lpel_main.c \
	src/lpel_hwloc.c src/sched/decentralised/sema.c \
	src/sched/decentralised/decen_scheduler.c \
	src/sched/decentralised/decen_scheduler.h \
	src/sched/decentralised/spmdext.c \
	src/sched/decentralised/spmdext.h \
	src/sched/decentralised/decen_task.c \
	src/sched/decentralised/decen_task.h \
	src/sched/decentralised/task_migration.h \
	src/sched/decentralised/task_migration.c \
	src/sched/decentralised/decen_worker.c \
	src/sched/decentralised/decen_worker.h \
	src/sched/decentralised/decen_taskqueue.c \
	src/sched/decentralised/decen_taskqueue.h \
	src/sched/decentralised/decen_stream.c \
	src/sched/decentralised/decen_stream.h \
	src/sched/decentralised/decen_buffer.c \
	src/sched/decentralised/decen_buffer.h \
	$(am__append_7) $(am__append_9) \
	$(am__append_11)
liblpel_la_CPPFLAGS = -I$(top_srcdir)/include \
	-I$(top_srcdir)/src/include \
	-I$(top_srcdir)/src/include/OpenComRTOS/posix32/include \
	$(am__append_5)
liblpel_la_LIBADD = $(LIBPCL_LA)
all: all-recursive

.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/Makefile_scc.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;
$(srcdir)/Makefile_scc.am:

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_la-mailbox.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_la-streamset.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_la-timing.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_la-lpelcfg.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_la-lpel_main.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_la-lpel_hwloc.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/$(am__dirstamp):
	@$(MKDIR_P) src/sched/decentralised
	@: > src/sched/decentralised/$(am__dirstamp)
src/sched/decentralised/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/sched/decentralised/$(DEPDIR)
	@: > src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-sema.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-decen_scheduler.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-spmdext.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-decen_task.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-task_migration.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-decen_worker.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-decen_taskqueue.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-decen_stream.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/sched/decentralised/liblpel_la-decen_buffer.lo:  \
	src/sched/decentralised/$(am__dirstamp) \
	src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
src/ctx/$(am__dirstamp):
	@$(MKDIR_P) src/ctx
	@: > src/ctx/$(am__dirstamp)
src/ctx/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/ctx/$(DEPDIR)
	@: > src/ctx/$(DEPDIR)/$(am__dirstamp)
src/ctx/liblpel_la-ctx_i386.lo: src/ctx/$(am__dirstamp) \
	src/ctx/$(DEPDIR)/$(am__dirstamp)
src/ctx/liblpel_la-ctx_amd64.lo: src/ctx/$(am__dirstamp) \
	src/ctx/$(DEPDIR)/$(am__dirstamp)
src/ctx/liblpel_la-ctx_amd64-mem.lo: src/ctx/$(am__dirstamp) \
	src/ctx/$(DEPDIR)/$(am__dirstamp)

liblpel.la: $(liblpel_la_OBJECTS) $(liblpel_la_DEPENDENCIES) $(EXTRA_liblpel_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) $(am_liblpel_la_rpath) $(liblpel_la_OBJECTS) $(liblpel_la_LIBADD) $(LIBS)
src/liblpel_hrc_la-mailbox.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_hrc_la-streamset.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_hrc_la-timing.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_hrc_la-lpelcfg.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_hrc_la-lpel_main.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/liblpel_hrc_la-lpel_hwloc.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/$(am__dirstamp):
	@$(MKDIR_P) src/sched/hierarchy
	@: > src/sched/hierarchy/$(am__dirstamp)
src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/sched/hierarchy/$(DEPDIR)
	@: > src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo:  \
	src/sched/hierarchy/$(am__dirstamp) \
	src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/liblpel_hrc_la-hrc_worker_init.lo:  \
	src/sched/hierarchy/$(am__dirstamp) \
	src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo:  \
	src/sched/hierarchy/$(am__dirstamp) \
	src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo:  \
	src/sched/hierarchy/$(am__dirstamp) \
	src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo:  \
	src/sched/hierarchy/$(am__dirstamp) \
	src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo:  \
	src/sched/hierarchy/$(am__dirstamp) \
	src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo:  \
	src/sched/hierarchy/$(am__dirstamp) \
	src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
src/ctx/liblpel_hrc_la-ctx_i386.lo: src/ctx/$(am__dirstamp) \
	src/ctx/$(DEPDIR)/$(am__dirstamp)
src/ctx/liblpel_hrc_la-ctx_amd64.lo: src/ctx/$(am__dirstamp) \
	src/ctx/$(DEPDIR)/$(am__dirstamp)
src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo: src/ctx/$(am__dirstamp) \
	src/ctx/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/scc/$(am__dirstamp):
	@$(MKDIR_P) src/sched/hierarchy/scc
	@: > src/sched/hierarchy/scc/$(am__dirstamp)
src/sched/hierarchy/scc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/sched/hierarchy/scc/$(DEPDIR)
	@: > src/sched/hierarchy/scc/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/scc/liblpel_hrc_la-scc_worker_init.lo:  \
	src/sched/hierarchy/scc/$(am__dirstamp) \
	src/sched/hierarchy/scc/$(DEPDIR)/$(am__dirstamp)
src/sched/hierarchy/scc/liblpel_hrc_la-scc_mailbox.lo:  \
	src/sched/hierarchy/scc/$(am__dirstamp) \
	src/sched/hierarchy/scc/$(DEPDIR)/$(am__dirstamp)

liblpel_hrc.la: $(liblpel_hrc_la_OBJECTS) $(liblpel_hrc_la_DEPENDENCIES) $(EXTRA_liblpel_hrc_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) $(am_liblpel_hrc_la_rpath) $(liblpel_hrc_la_OBJECTS) $(liblpel_hrc_la_LIBADD) $(LIBS)
modimpl/$(am__dirstamp):
	@$(MKDIR_P) modimpl
	@: > modimpl/$(am__dirstamp)
modimpl/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) modimpl/$(DEPDIR)
	@: > modimpl/$(DEPDIR)/$(am__dirstamp)
modimpl/liblpel_mon_la-monitoring.lo: modimpl/$(am__dirstamp) \
	modimpl/$(DEPDIR)/$(am__dirstamp)

liblpel_mon.la: $(liblpel_mon_la_OBJECTS) $(liblpel_mon_la_DEPENDENCIES) $(EXTRA_liblpel_mon_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) $(am_liblpel_mon_la_rpath) $(liblpel_mon_la_OBJECTS) $(liblpel_mon_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f modimpl/*.$(OBJEXT)
	-rm -f modimpl/*.lo
	-rm -f src/*.$(OBJEXT)
	-rm -f src/*.lo
	-rm -f src/ctx/*.$(OBJEXT)
	-rm -f src/ctx/*.lo
	-rm -f src/sched/decentralised/*.$(OBJEXT)
	-rm -f src/sched/decentralised/*.lo
	-rm -f src/sched/hierarchy/*.$(OBJEXT)
	-rm -f src/sched/hierarchy/*.lo
	-rm -f src/sched/hierarchy/scc/*.$(OBJEXT)
	-rm -f src/sched/hierarchy/scc/*.lo

distclean-compile:
	-rm -f *.tab.c

include modimpl/$(DEPDIR)/liblpel_mon_la-monitoring.Plo
include src/$(DEPDIR)/liblpel_hrc_la-lpel_hwloc.Plo
include src/$(DEPDIR)/liblpel_hrc_la-lpel_main.Plo
include src/$(DEPDIR)/liblpel_hrc_la-lpelcfg.Plo
include src/$(DEPDIR)/liblpel_hrc_la-mailbox.Plo
include src/$(DEPDIR)/liblpel_hrc_la-streamset.Plo
include src/$(DEPDIR)/liblpel_hrc_la-timing.Plo
include src/$(DEPDIR)/liblpel_la-lpel_hwloc.Plo
include src/$(DEPDIR)/liblpel_la-lpel_main.Plo
include src/$(DEPDIR)/liblpel_la-lpelcfg.Plo
include src/$(DEPDIR)/liblpel_la-mailbox.Plo
include src/$(DEPDIR)/liblpel_la-streamset.Plo
include src/$(DEPDIR)/liblpel_la-timing.Plo
include src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64-mem.Plo
include src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64.Plo
include src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_i386.Plo
include src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64-mem.Plo
include src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64.Plo
include src/ctx/$(DEPDIR)/liblpel_la-ctx_i386.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_buffer.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_scheduler.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_stream.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_task.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_taskqueue.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_worker.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-sema.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-spmdext.Plo
include src/sched/decentralised/$(DEPDIR)/liblpel_la-task_migration.Plo
include src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_buffer.Plo
include src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_stream.Plo
include src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_task.Plo
include src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_taskqueue.Plo
include src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_init.Plo
include src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_op.Plo
include src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-taskpriority.Plo
include src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_mailbox.Plo
include src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_worker_init.Plo

.S.o:
	$(AM_V_CPPAS)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CPPASCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CPPAS)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CPPASCOMPILE) -c -o $@ $<

.S.obj:
	$(AM_V_CPPAS)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CPPASCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CPPAS)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(CPPASCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.S.lo:
	$(AM_V_CPPAS)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCPPASCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CPPAS)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(LTCPPASCOMPILE) -c -o $@ $<

src/ctx/liblpel_la-ctx_i386.lo: src/ctx/ctx_i386.S
	$(AM_V_CPPAS)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT src/ctx/liblpel_la-ctx_i386.lo -MD -MP -MF src/ctx/$(DEPDIR)/liblpel_la-ctx_i386.Tpo -c -o src/ctx/liblpel_la-ctx_i386.lo `test -f 'src/ctx/ctx_i386.S' || echo '$(srcdir)/'`src/ctx/ctx_i386.S
	$(AM_V_at)$(am__mv) src/ctx/$(DEPDIR)/liblpel_la-ctx_i386.Tpo src/ctx/$(DEPDIR)/liblpel_la-ctx_i386.Plo
#	$(AM_V_CPPAS)source='src/ctx/ctx_i386.S' object='src/ctx/liblpel_la-ctx_i386.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o src/ctx/liblpel_la-ctx_i386.lo `test -f 'src/ctx/ctx_i386.S' || echo '$(srcdir)/'`src/ctx/ctx_i386.S

src/ctx/liblpel_la-ctx_amd64.lo: src/ctx/ctx_amd64.S
	$(AM_V_CPPAS)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT src/ctx/liblpel_la-ctx_amd64.lo -MD -MP -MF src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64.Tpo -c -o src/ctx/liblpel_la-ctx_amd64.lo `test -f 'src/ctx/ctx_amd64.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64.S
	$(AM_V_at)$(am__mv) src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64.Tpo src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64.Plo
#	$(AM_V_CPPAS)source='src/ctx/ctx_amd64.S' object='src/ctx/liblpel_la-ctx_amd64.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o src/ctx/liblpel_la-ctx_amd64.lo `test -f 'src/ctx/ctx_amd64.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64.S

src/ctx/liblpel_la-ctx_amd64-mem.lo: src/ctx/ctx_amd64-mem.S
	$(AM_V_CPPAS)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT src/ctx/liblpel_la-ctx_amd64-mem.lo -MD -MP -MF src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64-mem.Tpo -c -o src/ctx/liblpel_la-ctx_amd64-mem.lo `test -f 'src/ctx/ctx_amd64-mem.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64-mem.S
	$(AM_V_at)$(am__mv) src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64-mem.Tpo src/ctx/$(DEPDIR)/liblpel_la-ctx_amd64-mem.Plo
#	$(AM_V_CPPAS)source='src/ctx/ctx_amd64-mem.S' object='src/ctx/liblpel_la-ctx_amd64-mem.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o src/ctx/liblpel_la-ctx_amd64-mem.lo `test -f 'src/ctx/ctx_amd64-mem.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64-mem.S

src/ctx/liblpel_hrc_la-ctx_i386.lo: src/ctx/ctx_i386.S
	$(AM_V_CPPAS)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT src/ctx/liblpel_hrc_la-ctx_i386.lo -MD -MP -MF src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_i386.Tpo -c -o src/ctx/liblpel_hrc_la-ctx_i386.lo `test -f 'src/ctx/ctx_i386.S' || echo '$(srcdir)/'`src/ctx/ctx_i386.S
	$(AM_V_at)$(am__mv) src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_i386.Tpo src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_i386.Plo
#	$(AM_V_CPPAS)source='src/ctx/ctx_i386.S' object='src/ctx/liblpel_hrc_la-ctx_i386.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o src/ctx/liblpel_hrc_la-ctx_i386.lo `test -f 'src/ctx/ctx_i386.S' || echo '$(srcdir)/'`src/ctx/ctx_i386.S

src/ctx/liblpel_hrc_la-ctx_amd64.lo: src/ctx/ctx_amd64.S
	$(AM_V_CPPAS)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT src/ctx/liblpel_hrc_la-ctx_amd64.lo -MD -MP -MF src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64.Tpo -c -o src/ctx/liblpel_hrc_la-ctx_amd64.lo `test -f 'src/ctx/ctx_amd64.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64.S
	$(AM_V_at)$(am__mv) src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64.Tpo src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64.Plo
#	$(AM_V_CPPAS)source='src/ctx/ctx_amd64.S' object='src/ctx/liblpel_hrc_la-ctx_amd64.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o src/ctx/liblpel_hrc_la-ctx_amd64.lo `test -f 'src/ctx/ctx_amd64.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64.S

src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo: src/ctx/ctx_amd64-mem.S
	$(AM_V_CPPAS)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -MT src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo -MD -MP -MF src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64-mem.Tpo -c -o src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo `test -f 'src/ctx/ctx_amd64-mem.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64-mem.S
	$(AM_V_at)$(am__mv) src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64-mem.Tpo src/ctx/$(DEPDIR)/liblpel_hrc_la-ctx_amd64-mem.Plo
#	$(AM_V_CPPAS)source='src/ctx/ctx_amd64-mem.S' object='src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCASDEPMODE) $(depcomp) \
#	$(AM_V_CPPAS_no)$(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CCAS) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CCASFLAGS) $(CCASFLAGS) -c -o src/ctx/liblpel_hrc_la-ctx_amd64-mem.lo `test -f 'src/ctx/ctx_amd64-mem.S' || echo '$(srcdir)/'`src/ctx/ctx_amd64-mem.S

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

src/liblpel_la-mailbox.lo: src/mailbox.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_la-mailbox.lo -MD -MP -MF src/$(DEPDIR)/liblpel_la-mailbox.Tpo -c -o src/liblpel_la-mailbox.lo `test -f 'src/mailbox.c' || echo '$(srcdir)/'`src/mailbox.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_la-mailbox.Tpo src/$(DEPDIR)/liblpel_la-mailbox.Plo
#	$(AM_V_CC)source='src/mailbox.c' object='src/liblpel_la-mailbox.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_la-mailbox.lo `test -f 'src/mailbox.c' || echo '$(srcdir)/'`src/mailbox.c

src/liblpel_la-streamset.lo: src/streamset.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_la-streamset.lo -MD -MP -MF src/$(DEPDIR)/liblpel_la-streamset.Tpo -c -o src/liblpel_la-streamset.lo `test -f 'src/streamset.c' || echo '$(srcdir)/'`src/streamset.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_la-streamset.Tpo src/$(DEPDIR)/liblpel_la-streamset.Plo
#	$(AM_V_CC)source='src/streamset.c' object='src/liblpel_la-streamset.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_la-streamset.lo `test -f 'src/streamset.c' || echo '$(srcdir)/'`src/streamset.c

src/liblpel_la-timing.lo: src/timing.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_la-timing.lo -MD -MP -MF src/$(DEPDIR)/liblpel_la-timing.Tpo -c -o src/liblpel_la-timing.lo `test -f 'src/timing.c' || echo '$(srcdir)/'`src/timing.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_la-timing.Tpo src/$(DEPDIR)/liblpel_la-timing.Plo
#	$(AM_V_CC)source='src/timing.c' object='src/liblpel_la-timing.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_la-timing.lo `test -f 'src/timing.c' || echo '$(srcdir)/'`src/timing.c

src/liblpel_la-lpelcfg.lo: src/lpelcfg.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_la-lpelcfg.lo -MD -MP -MF src/$(DEPDIR)/liblpel_la-lpelcfg.Tpo -c -o src/liblpel_la-lpelcfg.lo `test -f 'src/lpelcfg.c' || echo '$(srcdir)/'`src/lpelcfg.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_la-lpelcfg.Tpo src/$(DEPDIR)/liblpel_la-lpelcfg.Plo
#	$(AM_V_CC)source='src/lpelcfg.c' object='src/liblpel_la-lpelcfg.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_la-lpelcfg.lo `test -f 'src/lpelcfg.c' || echo '$(srcdir)/'`src/lpelcfg.c

src/liblpel_la-lpel_main.lo: src/lpel_main.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_la-lpel_main.lo -MD -MP -MF src/$(DEPDIR)/liblpel_la-lpel_main.Tpo -c -o src/liblpel_la-lpel_main.lo `test -f 'src/lpel_main.c' || echo '$(srcdir)/'`src/lpel_main.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_la-lpel_main.Tpo src/$(DEPDIR)/liblpel_la-lpel_main.Plo
#	$(AM_V_CC)source='src/lpel_main.c' object='src/liblpel_la-lpel_main.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_la-lpel_main.lo `test -f 'src/lpel_main.c' || echo '$(srcdir)/'`src/lpel_main.c

src/liblpel_la-lpel_hwloc.lo: src/lpel_hwloc.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_la-lpel_hwloc.lo -MD -MP -MF src/$(DEPDIR)/liblpel_la-lpel_hwloc.Tpo -c -o src/liblpel_la-lpel_hwloc.lo `test -f 'src/lpel_hwloc.c' || echo '$(srcdir)/'`src/lpel_hwloc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_la-lpel_hwloc.Tpo src/$(DEPDIR)/liblpel_la-lpel_hwloc.Plo
#	$(AM_V_CC)source='src/lpel_hwloc.c' object='src/liblpel_la-lpel_hwloc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_la-lpel_hwloc.lo `test -f 'src/lpel_hwloc.c' || echo '$(srcdir)/'`src/lpel_hwloc.c

src/sched/decentralised/liblpel_la-sema.lo: src/sched/decentralised/sema.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-sema.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-sema.Tpo -c -o src/sched/decentralised/liblpel_la-sema.lo `test -f 'src/sched/decentralised/sema.c' || echo '$(srcdir)/'`src/sched/decentralised/sema.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-sema.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-sema.Plo
#	$(AM_V_CC)source='src/sched/decentralised/sema.c' object='src/sched/decentralised/liblpel_la-sema.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-sema.lo `test -f 'src/sched/decentralised/sema.c' || echo '$(srcdir)/'`src/sched/decentralised/sema.c

src/sched/decentralised/liblpel_la-decen_scheduler.lo: src/sched/decentralised/decen_scheduler.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-decen_scheduler.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_scheduler.Tpo -c -o src/sched/decentralised/liblpel_la-decen_scheduler.lo `test -f 'src/sched/decentralised/decen_scheduler.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_scheduler.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_scheduler.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_scheduler.Plo
#	$(AM_V_CC)source='src/sched/decentralised/decen_scheduler.c' object='src/sched/decentralised/liblpel_la-decen_scheduler.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-decen_scheduler.lo `test -f 'src/sched/decentralised/decen_scheduler.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_scheduler.c

src/sched/decentralised/liblpel_la-spmdext.lo: src/sched/decentralised/spmdext.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-spmdext.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-spmdext.Tpo -c -o src/sched/decentralised/liblpel_la-spmdext.lo `test -f 'src/sched/decentralised/spmdext.c' || echo '$(srcdir)/'`src/sched/decentralised/spmdext.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-spmdext.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-spmdext.Plo
#	$(AM_V_CC)source='src/sched/decentralised/spmdext.c' object='src/sched/decentralised/liblpel_la-spmdext.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-spmdext.lo `test -f 'src/sched/decentralised/spmdext.c' || echo '$(srcdir)/'`src/sched/decentralised/spmdext.c

src/sched/decentralised/liblpel_la-decen_task.lo: src/sched/decentralised/decen_task.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-decen_task.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_task.Tpo -c -o src/sched/decentralised/liblpel_la-decen_task.lo `test -f 'src/sched/decentralised/decen_task.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_task.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_task.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_task.Plo
#	$(AM_V_CC)source='src/sched/decentralised/decen_task.c' object='src/sched/decentralised/liblpel_la-decen_task.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-decen_task.lo `test -f 'src/sched/decentralised/decen_task.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_task.c

src/sched/decentralised/liblpel_la-task_migration.lo: src/sched/decentralised/task_migration.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-task_migration.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-task_migration.Tpo -c -o src/sched/decentralised/liblpel_la-task_migration.lo `test -f 'src/sched/decentralised/task_migration.c' || echo '$(srcdir)/'`src/sched/decentralised/task_migration.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-task_migration.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-task_migration.Plo
#	$(AM_V_CC)source='src/sched/decentralised/task_migration.c' object='src/sched/decentralised/liblpel_la-task_migration.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-task_migration.lo `test -f 'src/sched/decentralised/task_migration.c' || echo '$(srcdir)/'`src/sched/decentralised/task_migration.c

src/sched/decentralised/liblpel_la-decen_worker.lo: src/sched/decentralised/decen_worker.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-decen_worker.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_worker.Tpo -c -o src/sched/decentralised/liblpel_la-decen_worker.lo `test -f 'src/sched/decentralised/decen_worker.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_worker.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_worker.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_worker.Plo
#	$(AM_V_CC)source='src/sched/decentralised/decen_worker.c' object='src/sched/decentralised/liblpel_la-decen_worker.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-decen_worker.lo `test -f 'src/sched/decentralised/decen_worker.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_worker.c

src/sched/decentralised/liblpel_la-decen_taskqueue.lo: src/sched/decentralised/decen_taskqueue.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-decen_taskqueue.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_taskqueue.Tpo -c -o src/sched/decentralised/liblpel_la-decen_taskqueue.lo `test -f 'src/sched/decentralised/decen_taskqueue.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_taskqueue.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_taskqueue.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_taskqueue.Plo
#	$(AM_V_CC)source='src/sched/decentralised/decen_taskqueue.c' object='src/sched/decentralised/liblpel_la-decen_taskqueue.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-decen_taskqueue.lo `test -f 'src/sched/decentralised/decen_taskqueue.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_taskqueue.c

src/sched/decentralised/liblpel_la-decen_stream.lo: src/sched/decentralised/decen_stream.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-decen_stream.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_stream.Tpo -c -o src/sched/decentralised/liblpel_la-decen_stream.lo `test -f 'src/sched/decentralised/decen_stream.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_stream.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_stream.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_stream.Plo
#	$(AM_V_CC)source='src/sched/decentralised/decen_stream.c' object='src/sched/decentralised/liblpel_la-decen_stream.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-decen_stream.lo `test -f 'src/sched/decentralised/decen_stream.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_stream.c

src/sched/decentralised/liblpel_la-decen_buffer.lo: src/sched/decentralised/decen_buffer.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/decentralised/liblpel_la-decen_buffer.lo -MD -MP -MF src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_buffer.Tpo -c -o src/sched/decentralised/liblpel_la-decen_buffer.lo `test -f 'src/sched/decentralised/decen_buffer.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_buffer.c
	$(AM_V_at)$(am__mv) src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_buffer.Tpo src/sched/decentralised/$(DEPDIR)/liblpel_la-decen_buffer.Plo
#	$(AM_V_CC)source='src/sched/decentralised/decen_buffer.c' object='src/sched/decentralised/liblpel_la-decen_buffer.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/decentralised/liblpel_la-decen_buffer.lo `test -f 'src/sched/decentralised/decen_buffer.c' || echo '$(srcdir)/'`src/sched/decentralised/decen_buffer.c

src/liblpel_hrc_la-mailbox.lo: src/mailbox.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_hrc_la-mailbox.lo -MD -MP -MF src/$(DEPDIR)/liblpel_hrc_la-mailbox.Tpo -c -o src/liblpel_hrc_la-mailbox.lo `test -f 'src/mailbox.c' || echo '$(srcdir)/'`src/mailbox.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_hrc_la-mailbox.Tpo src/$(DEPDIR)/liblpel_hrc_la-mailbox.Plo
#	$(AM_V_CC)source='src/mailbox.c' object='src/liblpel_hrc_la-mailbox.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_hrc_la-mailbox.lo `test -f 'src/mailbox.c' || echo '$(srcdir)/'`src/mailbox.c

src/liblpel_hrc_la-streamset.lo: src/streamset.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_hrc_la-streamset.lo -MD -MP -MF src/$(DEPDIR)/liblpel_hrc_la-streamset.Tpo -c -o src/liblpel_hrc_la-streamset.lo `test -f 'src/streamset.c' || echo '$(srcdir)/'`src/streamset.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_hrc_la-streamset.Tpo src/$(DEPDIR)/liblpel_hrc_la-streamset.Plo
#	$(AM_V_CC)source='src/streamset.c' object='src/liblpel_hrc_la-streamset.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_hrc_la-streamset.lo `test -f 'src/streamset.c' || echo '$(srcdir)/'`src/streamset.c

src/liblpel_hrc_la-timing.lo: src/timing.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_hrc_la-timing.lo -MD -MP -MF src/$(DEPDIR)/liblpel_hrc_la-timing.Tpo -c -o src/liblpel_hrc_la-timing.lo `test -f 'src/timing.c' || echo '$(srcdir)/'`src/timing.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_hrc_la-timing.Tpo src/$(DEPDIR)/liblpel_hrc_la-timing.Plo
#	$(AM_V_CC)source='src/timing.c' object='src/liblpel_hrc_la-timing.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_hrc_la-timing.lo `test -f 'src/timing.c' || echo '$(srcdir)/'`src/timing.c

src/liblpel_hrc_la-lpelcfg.lo: src/lpelcfg.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_hrc_la-lpelcfg.lo -MD -MP -MF src/$(DEPDIR)/liblpel_hrc_la-lpelcfg.Tpo -c -o src/liblpel_hrc_la-lpelcfg.lo `test -f 'src/lpelcfg.c' || echo '$(srcdir)/'`src/lpelcfg.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_hrc_la-lpelcfg.Tpo src/$(DEPDIR)/liblpel_hrc_la-lpelcfg.Plo
#	$(AM_V_CC)source='src/lpelcfg.c' object='src/liblpel_hrc_la-lpelcfg.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_hrc_la-lpelcfg.lo `test -f 'src/lpelcfg.c' || echo '$(srcdir)/'`src/lpelcfg.c

src/liblpel_hrc_la-lpel_main.lo: src/lpel_main.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_hrc_la-lpel_main.lo -MD -MP -MF src/$(DEPDIR)/liblpel_hrc_la-lpel_main.Tpo -c -o src/liblpel_hrc_la-lpel_main.lo `test -f 'src/lpel_main.c' || echo '$(srcdir)/'`src/lpel_main.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_hrc_la-lpel_main.Tpo src/$(DEPDIR)/liblpel_hrc_la-lpel_main.Plo
#	$(AM_V_CC)source='src/lpel_main.c' object='src/liblpel_hrc_la-lpel_main.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_hrc_la-lpel_main.lo `test -f 'src/lpel_main.c' || echo '$(srcdir)/'`src/lpel_main.c

src/liblpel_hrc_la-lpel_hwloc.lo: src/lpel_hwloc.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/liblpel_hrc_la-lpel_hwloc.lo -MD -MP -MF src/$(DEPDIR)/liblpel_hrc_la-lpel_hwloc.Tpo -c -o src/liblpel_hrc_la-lpel_hwloc.lo `test -f 'src/lpel_hwloc.c' || echo '$(srcdir)/'`src/lpel_hwloc.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/liblpel_hrc_la-lpel_hwloc.Tpo src/$(DEPDIR)/liblpel_hrc_la-lpel_hwloc.Plo
#	$(AM_V_CC)source='src/lpel_hwloc.c' object='src/liblpel_hrc_la-lpel_hwloc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/liblpel_hrc_la-lpel_hwloc.lo `test -f 'src/lpel_hwloc.c' || echo '$(srcdir)/'`src/lpel_hwloc.c

src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo: src/sched/hierarchy/hrc_task.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo -MD -MP -MF src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_task.Tpo -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo `test -f 'src/sched/hierarchy/hrc_task.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_task.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_task.Tpo src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_task.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/hrc_task.c' object='src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_task.lo `test -f 'src/sched/hierarchy/hrc_task.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_task.c

src/sched/hierarchy/liblpel_hrc_la-hrc_worker_init.lo: src/sched/hierarchy/hrc_worker_init.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/liblpel_hrc_la-hrc_worker_init.lo -MD -MP -MF src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_init.Tpo -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_worker_init.lo `test -f 'src/sched/hierarchy/hrc_worker_init.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_worker_init.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_init.Tpo src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_init.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/hrc_worker_init.c' object='src/sched/hierarchy/liblpel_hrc_la-hrc_worker_init.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_worker_init.lo `test -f 'src/sched/hierarchy/hrc_worker_init.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_worker_init.c

src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo: src/sched/hierarchy/hrc_worker_op.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo -MD -MP -MF src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_op.Tpo -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo `test -f 'src/sched/hierarchy/hrc_worker_op.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_worker_op.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_op.Tpo src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_worker_op.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/hrc_worker_op.c' object='src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_worker_op.lo `test -f 'src/sched/hierarchy/hrc_worker_op.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_worker_op.c

src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo: src/sched/hierarchy/hrc_taskqueue.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo -MD -MP -MF src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_taskqueue.Tpo -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo `test -f 'src/sched/hierarchy/hrc_taskqueue.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_taskqueue.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_taskqueue.Tpo src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_taskqueue.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/hrc_taskqueue.c' object='src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_taskqueue.lo `test -f 'src/sched/hierarchy/hrc_taskqueue.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_taskqueue.c

src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo: src/sched/hierarchy/taskpriority.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo -MD -MP -MF src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-taskpriority.Tpo -c -o src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo `test -f 'src/sched/hierarchy/taskpriority.c' || echo '$(srcdir)/'`src/sched/hierarchy/taskpriority.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-taskpriority.Tpo src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-taskpriority.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/taskpriority.c' object='src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/liblpel_hrc_la-taskpriority.lo `test -f 'src/sched/hierarchy/taskpriority.c' || echo '$(srcdir)/'`src/sched/hierarchy/taskpriority.c

src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo: src/sched/hierarchy/hrc_stream.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo -MD -MP -MF src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_stream.Tpo -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo `test -f 'src/sched/hierarchy/hrc_stream.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_stream.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_stream.Tpo src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_stream.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/hrc_stream.c' object='src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_stream.lo `test -f 'src/sched/hierarchy/hrc_stream.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_stream.c

src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo: src/sched/hierarchy/hrc_buffer.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo -MD -MP -MF src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_buffer.Tpo -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo `test -f 'src/sched/hierarchy/hrc_buffer.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_buffer.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_buffer.Tpo src/sched/hierarchy/$(DEPDIR)/liblpel_hrc_la-hrc_buffer.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/hrc_buffer.c' object='src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/liblpel_hrc_la-hrc_buffer.lo `test -f 'src/sched/hierarchy/hrc_buffer.c' || echo '$(srcdir)/'`src/sched/hierarchy/hrc_buffer.c

src/sched/hierarchy/scc/liblpel_hrc_la-scc_worker_init.lo: src/sched/hierarchy/scc/scc_worker_init.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/scc/liblpel_hrc_la-scc_worker_init.lo -MD -MP -MF src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_worker_init.Tpo -c -o src/sched/hierarchy/scc/liblpel_hrc_la-scc_worker_init.lo `test -f 'src/sched/hierarchy/scc/scc_worker_init.c' || echo '$(srcdir)/'`src/sched/hierarchy/scc/scc_worker_init.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_worker_init.Tpo src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_worker_init.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/scc/scc_worker_init.c' object='src/sched/hierarchy/scc/liblpel_hrc_la-scc_worker_init.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/scc/liblpel_hrc_la-scc_worker_init.lo `test -f 'src/sched/hierarchy/scc/scc_worker_init.c' || echo '$(srcdir)/'`src/sched/hierarchy/scc/scc_worker_init.c

src/sched/hierarchy/scc/liblpel_hrc_la-scc_mailbox.lo: src/sched/hierarchy/scc/scc_mailbox.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/sched/hierarchy/scc/liblpel_hrc_la-scc_mailbox.lo -MD -MP -MF src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_mailbox.Tpo -c -o src/sched/hierarchy/scc/liblpel_hrc_la-scc_mailbox.lo `test -f 'src/sched/hierarchy/scc/scc_mailbox.c' || echo '$(srcdir)/'`src/sched/hierarchy/scc/scc_mailbox.c
	$(AM_V_at)$(am__mv) src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_mailbox.Tpo src/sched/hierarchy/scc/$(DEPDIR)/liblpel_hrc_la-scc_mailbox.Plo
#	$(AM_V_CC)source='src/sched/hierarchy/scc/scc_mailbox.c' object='src/sched/hierarchy/scc/liblpel_hrc_la-scc_mailbox.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_hrc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/sched/hierarchy/scc/liblpel_hrc_la-scc_mailbox.lo `test -f 'src/sched/hierarchy/scc/scc_mailbox.c' || echo '$(srcdir)/'`src/sched/hierarchy/scc/scc_mailbox.c

modimpl/liblpel_mon_la-monitoring.lo: modimpl/monitoring.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_mon_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT modimpl/liblpel_mon_la-monitoring.lo -MD -MP -MF modimpl/$(DEPDIR)/liblpel_mon_la-monitoring.Tpo -c -o modimpl/liblpel_mon_la-monitoring.lo `test -f 'modimpl/monitoring.c' || echo '$(srcdir)/'`modimpl/monitoring.c
	$(AM_V_at)$(am__mv) modimpl/$(DEPDIR)/liblpel_mon_la-monitoring.Tpo modimpl/$(DEPDIR)/liblpel_mon_la-monitoring.Plo
#	$(AM_V_CC)source='modimpl/monitoring.c' object='modimpl/liblpel_mon_la-monitoring.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(liblpel_mon_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o modimpl/liblpel_mon_la-monitoring.lo `test -f 'modimpl/monitoring.c' || echo '$(srcdir)/'`modimpl/monitoring.c

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf modimpl/.libs modimpl/_libs
	-rm -rf src/.libs src/_libs
	-rm -rf src/ctx/.libs src/ctx/_libs
	-rm -rf src/sched/decentralised/.libs src/sched/decentralised/_libs
	-rm -rf src/sched/hierarchy/.libs src/sched/hierarchy/_libs
	-rm -rf src/sched/hierarchy/scc/.libs src/sched/hierarchy/scc/_libs

distclean-libtool:
	-rm -f libtool config.lt

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LTLIBRARIES)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f modimpl/$(DEPDIR)/$(am__dirstamp)
	-rm -f modimpl/$(am__dirstamp)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/ctx/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/ctx/$(am__dirstamp)
	-rm -f src/sched/decentralised/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/sched/decentralised/$(am__dirstamp)
	-rm -f src/sched/hierarchy/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/sched/hierarchy/$(am__dirstamp)
	-rm -f src/sched/hierarchy/scc/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/sched/hierarchy/scc/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf modimpl/$(DEPDIR) src/$(DEPDIR) src/ctx/$(DEPDIR) src/sched/decentralised/$(DEPDIR) src/sched/hierarchy/$(DEPDIR) src/sched/hierarchy/scc/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf modimpl/$(DEPDIR) src/$(DEPDIR) src/ctx/$(DEPDIR) src/sched/decentralised/$(DEPDIR) src/sched/hierarchy/$(DEPDIR) src/sched/hierarchy/scc/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-libLTLIBRARIES

.MAKE: $(am__recursive_targets) install-am install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-cscope clean-generic \
	clean-libLTLIBRARIES clean-libtool cscope cscopelist-am ctags \
	ctags-am dist dist-all dist-bzip2 dist-gzip dist-lzip \
	dist-shar dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-libLTLIBRARIES \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-libLTLIBRARIES


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
